const PrivacyPolicy = () => {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12 text-gray-200 leading-relaxed">
      <h1 className="text-4xl font-bold mb-6 text-white">Privacy Policy</h1>
      <p className="text-sm text-gray-400 mb-8">
        Last updated: September 26, 2025
      </p>

      <p className="mb-4">
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p className="mb-6">
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy. This Privacy Policy has been
        {/* created with the help of the{" "}
        <a
          href="https://www.termsfeed.com/privacy-policy-generator/"
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-600 underline"
        >
          Privacy Policy Generator
        </a> */}
        .
      </p>
      <hr className="border-gray-700 my-8" />

      <h2 className="text-2xl font-semibold text-blue-400 mt-8 mb-4">
        Interpretation and Definitions
      </h2>
      <h3 className="text-xl font-medium text-white mt-6 mb-2">
        Interpretation
      </h3>
      <p className="mb-4">
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>

      <h3 className="text-xl font-medium text-white mt-6 mb-2">Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul className="list-disc pl-6 space-y-2 mb-6">
        <li>
          <strong className="text-white">Account</strong> means a unique account created for You to
          access our Service or parts of our Service.
        </li>
        <li>
          <strong>Affiliate</strong> means an entity that controls, is
          controlled by or is under common control with a party, where "control"
          means ownership of 50% or more of the shares, equity interest or other
          securities entitled to vote for election of directors or other
          managing authority.
        </li>
        <li>
          <strong className="text-white">Company</strong> (referred to as either "the Company", "We",
          "Us" or "Our" in this Agreement) refers to ADSSY MEDIA.
        </li>
        <li>
          <strong className="text-white">Cookies</strong> are small files that are placed on Your
          computer, mobile device or any other device by a website, containing
          the details of Your browsing history on that website among its many
          uses.
        </li>
        <li>
          <strong>Country</strong> refers to: Telangana, India
        </li>
        <li>
          <strong>Device</strong> means any device that can access the Service
          such as a computer, a cellphone or a digital tablet.
        </li>
        <li>
          <strong>Personal Data</strong> is any information that relates to an
          identified or identifiable individual.
        </li>
        <li>
          <strong>Service</strong> refers to the Website.
        </li>
        <li>
          <strong>Service Provider</strong> means any natural or legal person
          who processes the data on behalf of the Company.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically,
          either generated by the use of the Service or from the Service
          infrastructure itself (for example, the duration of a page visit).
        </li>
        <li>
          <strong>Website</strong> refers to ADSSY MEDIA, accessible from{" "}
          <a
            href="https://www.adssymedia.com/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-600 underline"
          >
            https://www.adssymedia.com/
          </a>
        </li>
        <li>
          <strong>You</strong> means the individual accessing or using the
          Service, or the company, or other legal entity on behalf of which such
          individual is accessing or using the Service, as applicable.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold mt-6 mb-2">
        Collecting and Using Your Personal Data
      </h2>
      <h3 className="text-xl font-medium mt-4 mb-1">Types of Data Collected</h3>

      <h4 className="text-lg font-semibold mt-4">Personal Data</h4>
      <p>
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>
      <ul className="list-disc pl-6 space-y-1">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Usage Data</li>
      </ul>

      {/* ---- You continue in the same JSX pattern for the rest of your text ---- */}
      {/* I shortened here to keep it readable, but you can paste everything in */}

      <h2 className="text-2xl font-semibold mt-6 mb-2">Contact Us</h2>
      <p>
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <ul className="list-disc pl-6 space-y-2">
        <li>
          Email:{" "}
          <a
            href="mailto:adssymedia@gmail.com"
            className="text-blue-400 underline"
          >
            adssymedia@gmail.com
          </a>
        </li>
        <li>
          By visiting this page on our website:{" "}
          <a
            href="https://www.adssymedia.com/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-600 underline"
          >
            https://www.adssymedia.com/
          </a>
        </li>
      </ul>
    </div>
  );
};

export default PrivacyPolicy;
